pronunciation = {
    "Aceu": ["a-sue"],
    "Akanemsko": ["a-k-a nem-skoh"],
    "Alluux": ["al-ux"],
    "Alveussanctuary": ["al-vey-us sanctuary"],
    "Amouranth": ["amouranth"],
    "Anna cramling": ["Anna Cram-ling"],
    "Anthonyz": ["anthony-z"],
    "Ariasaki": ["aria sah-key"],
    "Atrioc": ["ey-tree-ock"],
    "Austinshow": ["austin show"],
    "Avghans": ["af-gans"],
    "Blau": ["blau"],
    "Boomerna": ["boomer N-A"],
    "Botezlive": ["bow-tez live"],
    "Boxbox": ["box-box"],
    "Brittt": ["brit"],
    "Brookeab": ["brooke a-b"],
    "Buddha": ["boo-duh"],
    "Chrisnxtdoor": ["Chris Next Door"],
    "Cinna": ["sin-ah"],
    "Clix": ["Clicks"],
    "Codemiko": ["code mee-ko"],
    "Connoreatspants": ["connor eats pants"],
    "Cooksux": ["cook sucks"],
    "Crazyslick": ["crazy slick"],
    "Cyr": ["seer"],
    "Daily Dose of Internet": ["daily dose of internet"],
    "Disguised toast": ["disguised toast"],
    "Dougdoug": ["doug doug"],
    "Emiru": ["emy-roo"],
    "Emma langevin": ["emma lawn-gevin"],
    "Erobb221": ["e-rob 2-2-1"],
    "Esfandtv": ["esfand-tv"],
    "Extraemily": ["extra-emily"],
    "Fanfan": ["fan-fan"],
    "Flats": ["flats"],
    "Flexinja": ["flex inja"],
    "FoolishGamers": ["foolish gamers"],
    "Forsen": ["for-sen"],
    "Frogan": ["fro-gan"],
    "Fuslie": ["fooz-ly"],
    "Hachubby": ["ha-chuh-bee"],
    "HasanAbi": ["HA-san ah-bee"],
    "HealthyGamer": ["healthy gamer"],
    "Igumdrop": ["i-gum-drop"],
    "Iitztimmy": ["it's timmy"],
    "Im_dontai": ["I'm dawn-tay"],
    "Itshafu": ["it's ha-foo"],
    "Itsryanhiga": ["it's ryan hee-gah"],
    "Jerma985": ["jerma 9-8-5"],
    "Jinnytty": ["jinny-t-t-y"],
    "Karl jacobs": ["karl jacobs"],
    "Knut": ["knoot"],
    "Kyedae": ["kai-day"],
    "Kyootbot": ["cute bot"],
    "Lilypichu": ["lily-peach-oo"],
    "Ludwig": ["ludwig"],
    "Masayoshi": ["masayoshi"],
    "Maximum": ["maximum"],
    "Meatcanyon": ["meat canyon"],
    "Michael reeves": ["michael reeves"],
    "Miyoung": ["mee-young"],
    "Mizkif": ["miz-kif"],
    "Moistcritical": ["moist critical"],
    "Myth": ["myth"],
    "Paymoneywubby": ["pay-money-wubby"],
    "Peterpark": ["peter-park"],
    "Pointcrow": ["point-crow"],
    "Pokimane": ["pokimon"],
    "Prezoh": ["preh-so"],
    "Purplecliffe": ["purple cliff"],
    "QTCinderella": ["cutie-cinderella"],
    "Quarterjade": ["quarter jade"],
    "Ranboo": ["ranboo"],
    "Ray c": ["ray see"],
    "Roflgator": ["raw-fall gator"],
    "Russel": ["russel"],
    "Samwitch": ["sam-witch"],
    "Sapnap": ["sap nap"],
    "Sashagrey": ["sasha grey"],
    "Scarra": ["sca-rah"],
    "Seanic": ["sean-ick"],
    "Shxtou": ["show-doe"],
    "Simply": ["simply"],
    "Squeex": ["squeaks"],
    "Stanz": ["stanz"],
    "Starsmitten": ["star-smitten"],
    "STPeach": ["s-t peach"],
    "Sweet_anita": ["sweet anita"],
    "Sydeon": ["sydeon"],
    "Sykkuno": ["psych-uno"],
    "Symfuhny": ["symphony"],
    "Tarik": ["tarik"],
    "Ted nivison": ["ted nivison"],
    "Tenz": ["tense"],
    "Tinakitten": ["tina kitten"],
    "Tubbo": ["tub-oh"],
    "Valkyrae": ["val-key-ray"]
}