pronunciation = {
    "Akanemsko": ["a-k-a nem-skoh"],
    "Alluux": ["al-ux"],
    "Alveussanctuary": ["al-vey-us sanctuary"],
    "Amouranth": ["amouranth"],
    "Anthonyz": ["anthony-z"],
    "Ariasaki": ["aria sah-key"],
    "Atrioc": ["ey-trioc"],
    "Avghans": ["af-gans"],
    "Blau": ["blau"],
    "Botezlive": ["bow-tez live"],
    "Boxbox": ["box-box"],
    "Brittt": ["brit"],
    "Cinna": ["sin-ah"],
    "Codemiko": ["code mee-ko"],
    "Connoreatspants": ["connor eats pants"],
    "Cyr": ["seer"],
    "Daily Dose of Internet": ["daily dose of internet"],
    "Emiru": ["emy-roo"],
    "Erobb221": ["e-rob 2-2-1"],
    "Esfandtv": ["esfand-tv"],
    "Extraemily": ["extra-emily"],
    "Fanfan": ["fan-fan"],
    "FoolishGamers": ["foolish gamers"],
    "Forsen": ["for-sen"],
    "Frogan": ["fro-gan"],
    "Fuslie": ["fooz-ly"],
    "Hachubby": ["ha-chuh-bee"],
    "HasanAbi": ["HA-san ah-bee"],
    "HealthyGamer": ["healthy gamer"],
    "Igumdrop": ["i-gum-drop"],
    "Itshafu": ["it's ha-foo"],
    "Itsryanhiga": ["it's ryan hee-gah"],
    "Jerma985": ["jerma 9-8-5"],
    "Jinnytty": ["jinny-t-t-y"],
    "Kyedae": ["kai-day"],
    "Lilypichu": ["lily-peach-oo"],
    "Ludwig": ["ludwig"],
    "Masayoshi": ["masayoshi"],
    "Mizkif": ["miz-kif"],
    "Paymoneywubby": ["pay-money-wubby"],
    "Peterpark": ["peter-park"],
    "Pointcrow": ["point-crow"],
    "Pokimane": ["pokimon"],
    "QTCinderella": ["cutie-cinderella"],
    "Quarterjade": ["quarter jade"],
    "Samwitch": ["sam-witch"],
    "Sashagrey": ["sasha grey"],
    "Seanic": ["sean-ick"],
    "Shxtou": ["show-doe"],
    "Squeex": ["squeaks"],
    "Stanz": ["stanz"],
    "Starsmitten": ["star-smitten"],
    "STPeach": ["s-t peach"],
    "Sweet_anita": ["sweet anita"],
    "Sydeon": ["sydeon"],
    "Sykkuno": ["psych-uno"],
    "Tarik": ["tarik"],
    "Tenz": ["tense"],
    "Valkyrae": ["val-key-ray"]
}