pronunciation = {
    "Aceu": ["a-sue"],
    "Agent00": ["agent 0 0"],
    "Akanemsko": ["a-k-a nem-skoh"],
    "Alluux": ["al-ux"],
    "Alveussanctuary": ["al-vey-us sanctuary"],
    "Amouranth": ["amouranth"],
    "Anna cramling": ["Anna Cram-ling"],
    "Anthonyz": ["anthony-z"],
    "Ariasaki": ["aria sah-key"],
    "ARIatHOME": ["ah-ree at home"],
    "Asianjeff": ["asian jeff"],
    "Asmongold": ["as-mon-gold"],
    "Atrioc": ["ey-tree-ock"],
    "Austinshow": ["austin show"],
    "Avghans": ["af-gans"],
    "Bigbossboze": ["big boss boze"],
    "Blau": ["blau"],
    "Boomerna": ["boomer N-A"],
    "Botezlive": ["bow-tez live"],
    "Boxbox": ["box-box"],
    "Brittt": ["brit"],
    "Brookeab": ["brooke a-b"],
    "Buddha": ["boo-duh"],
    "Cardboard_cowboy": ["cardboard cowboy"],
    "Caseoh_": ["case-oh"],
    "Cdawgva": ["c dog v-a"],
    "Cellbit": ["cell bit"],
    "Chiblee": ["chib-lee"],
    "Chrisnxtdoor": ["Chris Next Door"],
    "Cinna": ["sin-ah"],
    "Clix": ["Clicks"],
    "Codemiko": ["code mee-ko"],
    "Connoreatspants": ["connor eats pants"],
    "Cooksux": ["cook sucks"],
    "Crazyslick": ["crazy slick"],
    "Cyr": ["seer"],
    "Daily Dose of Internet": ["daily dose of internet"],
    "Disguised toast": ["disguised toast"],
    "Distortion2": ["distortion 2"],
    "Dougdoug": ["doug doug"],
    "Emilyywang": ["emily wang"],
    "Emiru": ["emy-roo"],
    "Emma langevin": ["emma lawn-gevin"],
    "Erobb221": ["e-rob 2-2-1"],
    "Esfandtv": ["esfand-tv"],
    "Etoiles": ["eh-twah"],
    "Everythingnowshow": ["Everything now show"],
    "Extraemily": ["extra-emily"],
    "Fanfan": ["fan-fan"],
    "Fanum": ["fan-uhm"],
    "Filian": ["filian"],
    "Flats": ["flats"],
    "Flexinja": ["flex inja"],
    "FoolishGamers": ["foolish gamers"],
    "Forsen": ["for-sen"],
    "Frogan": ["fro-gan"],
    "Fuslie": ["fooz-ly"],
    "Gappyv": ["gappy vee"],
    "GM Hikaru": ["GM he-CAR-oo"],
    "Gothamchess": ["gotham chess"],
    "Hachubby": ["ha-chuh-bee"],
    "Hansumfella": ["handsome fella"],
    "HasanAbi": ["HA-san ah-bee"],
    "HealthyGamer": ["healthy gamer"],
    "Hitch": ["hitch"],
    "Hugrybox": ["hungry box"],
    "Igumdrop": ["i-gum-drop"],
    "Iitztimmy": ["it's timmy"],
    "Im_dontai": ["I'm dawn-tay"],
    "Ironmouse": ["iron mouse"],
    "Itshafu": ["it's ha-foo"],
    "Itsryanhiga": ["it's ryan hee-gah"],
    "Jerma985": ["jerma 9-8-5"],
    "Jinnytty": ["jinny-t-t-y"],
    "Jynxzi": ["jink-see"],
    "K3soju": ["k-3-soju"],
    "Kaicenat": ["kai cenat"],
    "Karl jacobs": ["karl jacobs"],
    "Knut": ["knoot"],
    "Kyedae": ["kai-day"],
    "Kyootbot": ["cute bot"],
    "Lanaaamaee": ["lana may"],
    "Liam": ["lee-am"],
    "Lilypichu": ["lily-peach-oo"],
    "Loltyler1": ["tyler one"],
    "Lord_kebun": ["lord kevin"],
    "Ludwig": ["ludwig"],
    "Lydiaviolet": ["lydia violet"],
    "Mari": ["mah-ree"],
    "Masayoshi": ["masayoshi"],
    "Maximilian_dood": ["Maximilian dude"],
    "Maximum": ["maximum"],
    "Meatcanyon": ["meat canyon"],
    "Michael reeves": ["michael reeves"],
    "Miyoung": ["mee-young"],
    "Mizkif": ["miz-kif"],
    "Moistcritical": ["moist critical"],
    "Myth": ["myth"],
    "Nicewigg": ["nice wig"],
    "Nmplol": ["n-m-p-l-o-l"],
    "Noraexplorer": ["nora explorer"],
    "Omie": ["ow-mee"],
    "Onigiri": ["onigiri"],
    "Papesan": ["pup san"],
    "Paymoneywubby": ["pay-money-wubby"],
    "Peterpark": ["peter-park"],
    "Piratesoftware": ["pirate software"],
    "Plaqueboymax": ["plack-boy-max"],
    "Pointcrow": ["point-crow"],
    "Pokimane": ["pokimon"],
    "Prezoh": ["preh-so"],
    "Purplecliffe": ["purple cliff"],
    "QTCinderella": ["cutie-cinderella"],
    "Quackity": ["quack-itty"],
    "Quarterjade": ["quarter jade"],
    "Ranboo": ["ranboo"],
    "Ray c": ["ray see"],
    "Rdcgaming": ["r-d-c gaming"],
    "Rivers_gg": ["rivers g-g"],
    "Robcdee": ["rob c d"],
    "Roflgator": ["raw-fall gator"],
    "RubberRoss ": ["rubber ross"],
    "Russel": ["russel"],
    "S0mcs": ["sawm c-s"],
    "Sajam": ["say-jam"],
    "Samwitch": ["sam-witch"],
    "Sapnap": ["sap nap"],
    "Sashagrey": ["sasha grey"],
    "Scarra": ["sca-rah"],
    "Seandablack": ["shawn-the-black"],
    "Seanic": ["sean-ick"],
    "Shroud": ["shroud"],
    "Shxtou": ["show-doe"],
    "Simply": ["simply"],
    "Sodapoppin": ["soda-pop-in"],
    "Squeex": ["squeaks"],
    "Stanz": ["stanz"],
    "Starsmitten": ["star-smitten"],
    "STPeach": ["s-t peach"],
    "Supertf": ["super t-f"],
    "Sweet_anita": ["sweet anita"],
    "Sydeon": ["sydeon"],
    "Sykkuno": ["psych-uno"],
    "Symfuhny": ["symphony"],
    "Sypherpk": ["sigh-fer-p-k"],
    "Tarik": ["tarik"],
    "Ted nivison": ["ted nivison"],
    "Tenz": ["tense"],
    "Tinakitten": ["tina kitten"],
    "triciaisabirdy": ["tricia is a birdy"],
    "Tubbo": ["tub-oh"],
    "Valkyrae": ["val-key-ray"],
    "Vedal987": ["beetle 9-8-7"],
    "Willneff": ["will neff"],
    "Wirtual": ["virtual"],
    "Xqc": ["x-q-c"],
    "Yourragegaming": ["your rage gaming"],
    "Yvonnie": ["ee-vohn-ee"]
}